[package]
name = "iyes_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
path = "../bevy"
default-features = false

[dev-dependencies]
bevy = { path = "../bevy" }
rand = "0.8.5"

