[package]
name = "iyes_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
version = "0.14.0"
default-features = false

[dev-dependencies]
bevy = "0.14.0"
rand = "0.8.5"

